"use client";

import { AnimatePresence, motion } from "framer-motion";
import { Check, ShoppingBag, X } from "lucide-react";
import { useCart } from "@/context/CartContext";
import { CartItem } from "./CartItem";

export function CartDrawer() {
  const { items, itemCount, subtotal, isOpen, closeCart, toast } = useCart();
  return <><AnimatePresence>{isOpen && <><motion.button aria-label="Close cart" onClick={closeCart} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[70] cursor-default bg-ink/30 backdrop-blur-[2px]"/><motion.aside role="dialog" aria-modal="true" aria-label="Shopping cart" initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} transition={{ type: "spring", damping: 29, stiffness: 280 }} className="fixed inset-y-0 right-0 z-[71] flex w-full max-w-[460px] flex-col bg-white shadow-2xl"><header className="flex items-center justify-between border-b border-black/8 px-6 py-5"><div><p className="eyebrow">Your selection</p><h2 className="mt-1 text-xl font-extrabold tracking-tight">Shopping bag <span className="text-black/35">({itemCount})</span></h2></div><button onClick={closeCart} aria-label="Close cart" className="grid size-10 place-items-center rounded-full bg-cloud transition hover:bg-black hover:text-white"><X size={19}/></button></header>
    {items.length > 0 ? <><ul className="flex-1 space-y-5 overflow-y-auto px-6 py-6"><AnimatePresence initial={false}>{items.map((item) => <CartItem item={item} key={item.name}/>)}</AnimatePresence></ul><footer className="border-t border-black/8 bg-cloud/60 px-6 py-5"><div className="flex justify-between text-sm"><span className="text-black/55">Subtotal · {itemCount} {itemCount === 1 ? "item" : "items"}</span><strong>${subtotal.toFixed(2)}</strong></div><p className="mt-2 text-[11px] text-black/45">Taxes and delivery calculated at checkout.</p><button className="mt-5 flex w-full items-center justify-center gap-2 rounded-full bg-ink px-5 py-3.5 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:shadow-lg">Secure checkout <span aria-hidden>→</span></button><button onClick={closeCart} className="mt-2 w-full rounded-full border border-black/10 bg-white px-5 py-3 text-sm font-bold transition hover:bg-cloud">Continue shopping</button></footer></> : <div className="flex flex-1 flex-col items-center justify-center px-7 text-center"><div className="grid size-20 place-items-center rounded-full bg-mint"><ShoppingBag size={30}/></div><h3 className="mt-6 text-xl font-extrabold">Your cart is empty.</h3><p className="mt-2 max-w-[260px] text-sm leading-6 text-black/50">A good find is waiting for you in the Luma edit.</p><button onClick={closeCart} className="mt-7 rounded-full bg-ink px-5 py-3 text-sm font-bold text-white">Continue shopping</button></div>}</motion.aside></>}</AnimatePresence><AnimatePresence>{toast && <motion.div role="status" initial={{ opacity: 0, y: 18, scale: .96 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 12 }} className="fixed bottom-5 left-1/2 z-[80] flex -translate-x-1/2 items-center gap-2 rounded-full bg-ink px-4 py-3 text-sm font-semibold text-white shadow-2xl"><span className="grid size-5 place-items-center rounded-full bg-emerald-400 text-ink"><Check size={13}/></span>{toast}</motion.div>}</AnimatePresence></>;
}
