"use client";
import { AnimatePresence, motion } from "framer-motion";
import Link from "next/link";
import { ArrowRight, Check, ChevronLeft, ChevronRight, Heart, Menu, PackageCheck, Plus, Search, ShieldCheck, Star, Truck, X, Zap } from "lucide-react";
import { useEffect, useState } from "react";
import { categories, products } from "@/lib/data";
import { Button, Reveal } from "./ui";
import { CartBadge } from "./cart/CartBadge";
import { useCart } from "@/context/CartContext";

const nav = ["Shop", "Categories", "New arrivals", "Journal"];
const brands = ["SONY", "adidas", "NIKE", "SAMSUNG", "PUMA", "BOSE"];
const testimonials = [{name:"Amelia Parker",role:"Verified customer",quote:"Luma has quietly become my favorite place to find pieces that feel considered, not just trendy.",initials:"AP"},{name:"Noah Williams",role:"Verified customer",quote:"Everything from the packaging to delivery felt effortless. Exactly the kind of shopping experience I want.",initials:"NW"},{name:"Mia Chen",role:"Verified customer",quote:"The edit is impeccable. I found three things I actually use every single day.",initials:"MC"}];

export default function Storefront() {
 const [menu,setMenu]=useState(false), [email,setEmail]=useState(""), [subscribed,setSubscribed]=useState(false), [active,setActive]=useState(0), [seconds,setSeconds]=useState(71994);
 const { addItem } = useCart();
 useEffect(()=>{const id=setInterval(()=>setSeconds(s=>s>0?s-1:0),1000);return()=>clearInterval(id)},[]);
 const time = [Math.floor(seconds/3600),Math.floor(seconds/60)%60,seconds%60].map(x=>String(x).padStart(2,"0"));
 return <main className="overflow-hidden">
  <nav className="sticky top-0 z-50 border-b border-black/5 bg-cloud/75 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 lg:px-8">
   <a href="#top" className="text-2xl font-extrabold tracking-[-.1em]" aria-label="Luma home">luma<span className="text-emerald-500">.</span></a>
   <div className="hidden items-center gap-7 text-sm font-semibold md:flex">{nav.map(x=><a className="transition hover:text-emerald-600" href={'#'+x.toLowerCase().replace(' ','-')} key={x}>{x}</a>)}</div>
   <div className="flex items-center gap-1"><button aria-label="Search" className="grid size-10 place-items-center rounded-full hover:bg-black/5"><Search size={19}/></button><button aria-label="Wishlist" className="hidden sm:grid size-10 place-items-center rounded-full hover:bg-black/5"><Heart size={19}/></button><CartBadge/><button onClick={()=>setMenu(true)} aria-label="Open menu" className="grid size-10 place-items-center rounded-full bg-ink text-white md:hidden"><Menu size={18}/></button></div>
  </div></nav>
  <AnimatePresence>{menu&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[60] bg-ink p-7 text-white"><div className="flex justify-between"><span className="text-2xl font-extrabold tracking-[-.1em]">luma.</span><button onClick={()=>setMenu(false)} aria-label="Close menu"><X/></button></div><div className="mt-20 flex flex-col gap-7 text-4xl font-bold">{nav.map(x=><a key={x} onClick={()=>setMenu(false)} href={'#'+x.toLowerCase().replace(' ','-')}>{x}</a>)}</div></motion.div>}</AnimatePresence>

  <section id="top" className="px-4 pb-4 pt-4 sm:px-6 lg:px-8"><div className="relative mx-auto grid min-h-[660px] max-w-7xl overflow-hidden rounded-[2rem] bg-[#dff3e7] lg:grid-cols-[.95fr_1.05fr]">
   <div className="relative z-10 flex flex-col justify-center px-7 py-16 sm:px-14 lg:px-16"><motion.p initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{delay:.1}} className="eyebrow mb-6 flex items-center gap-2"><span className="size-2 rounded-full bg-emerald-500"/> Curated for everyday</motion.p><motion.h1 initial={{opacity:0,y:26}} animate={{opacity:1,y:0}} transition={{delay:.2,duration:.7}} className="display max-w-xl text-6xl font-extrabold leading-[.9] sm:text-7xl lg:text-8xl">Made for the<br/><i className="font-medium">way you live.</i></motion.h1><motion.p initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{delay:.36}} className="mt-7 max-w-md text-base leading-7 text-black/60">Thoughtfully selected objects for your home, your wardrobe, and every space in between.</motion.p><motion.div initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{delay:.46}} className="mt-8 flex flex-wrap gap-3"><Button onClick={()=>document.getElementById('shop')?.scrollIntoView()}>Shop the edit</Button><a href="#categories" className="rounded-full border border-black/15 px-5 py-3 text-sm font-bold hover:bg-white/50">Explore categories</a></motion.div></div>
   <motion.div initial={{opacity:0,scale:1.04}} animate={{opacity:1,scale:1}} transition={{duration:1}} className="relative min-h-[430px] overflow-hidden lg:min-h-0"><img className="h-full w-full object-cover" src="https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1400&q=85" alt="Curated modern living room"/><div className="absolute inset-0 bg-gradient-to-t from-black/25 to-transparent"/><motion.div animate={{y:[0,-8,0]}} transition={{repeat:Infinity,duration:4}} className="absolute bottom-6 left-6 rounded-2xl border border-white/35 bg-white/65 p-4 backdrop-blur-md"><p className="eyebrow">The home edit</p><p className="mt-1 text-sm font-bold">Spaces that feel like you</p></motion.div></motion.div>
  </div></section>
  <section className="mx-auto max-w-7xl px-5 py-11 sm:px-8"><p className="eyebrow mb-7 text-center text-black/40">Loved by people who love good design</p><div className="grid grid-cols-3 items-center gap-y-7 text-center text-lg font-extrabold tracking-tight text-black/45 sm:grid-cols-6">{brands.map(b=><span key={b}>{b}</span>)}</div></section>

  <section id="categories" className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><Reveal><div className="flex items-end justify-between"><div><p className="eyebrow text-emerald-700">Start somewhere good</p><h2 className="display mt-3 text-4xl font-extrabold sm:text-5xl">Shop by feeling.</h2></div><a href="#shop" className="hidden items-center gap-1 text-sm font-bold sm:flex">View all <ArrowRight size={16}/></a></div></Reveal><div className="mt-9 grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">{categories.map((c,i)=>{const Icon=c.icon;return <Reveal delay={i*.06} key={c.name}><a href="#shop" className="image-zoom group relative block aspect-[.72] overflow-hidden rounded-2xl bg-gray-200"><img loading="lazy" className="h-full w-full object-cover" src={c.image} alt={c.name}/><div className="absolute inset-0 bg-gradient-to-t from-black/65 via-black/0 to-transparent"/><div className="absolute bottom-0 p-4 text-white"><Icon size={18}/><h3 className="mt-6 text-sm font-bold">{c.name}</h3><p className="mt-1 text-xs text-white/75">{c.caption}</p></div></a></Reveal>})}</div></section>

  <section id="shop" className="bg-white py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Reveal><div className="flex items-end justify-between"><div><p className="eyebrow text-emerald-700">The Luma edit</p><h2 className="display mt-3 text-4xl font-extrabold sm:text-5xl">Worth making room for.</h2></div><a href="#" className="hidden text-sm font-bold sm:block">Shop all products →</a></div></Reveal><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.map((p,i)=><Reveal delay={i*.08} key={p.name}><article className="group"><Link href={`/product/${p.id}`} aria-label={`View ${p.name}`} className="image-zoom relative block aspect-square overflow-hidden rounded-2xl bg-cloud focus:outline-none focus:ring-2 focus:ring-ink focus:ring-offset-2"><img loading="lazy" src={p.image} alt={p.name} className="h-full w-full object-cover"/><span className="absolute left-3 top-3 rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase tracking-wider">{p.badge}</span><span aria-hidden="true" className="absolute right-3 top-3 grid size-9 place-items-center rounded-full bg-white/90 opacity-100 sm:opacity-0 sm:transition sm:group-hover:opacity-100"><Heart size={16}/></span><span className="absolute bottom-3 left-3 right-3 rounded-xl bg-white py-3 text-center text-xs font-bold opacity-100 sm:translate-y-3 sm:opacity-0 sm:transition sm:group-hover:translate-y-0 sm:group-hover:opacity-100">Quick view</span></Link><div className="flex items-start justify-between pt-4"><div><p className="text-[11px] text-black/45">{p.category}</p><Link href={`/product/${p.id}`} className="mt-1 block text-sm font-bold hover:underline">{p.name}</Link><p className="mt-1 text-sm font-bold">${p.price} {p.old>0&&<span className="ml-1 text-xs font-normal text-black/35 line-through">${p.old}</span>}</p></div><div className="text-right"><span className="flex items-center gap-1 text-xs font-bold"><Star size={13} fill="currentColor"/> {p.rating}</span><button onClick={()=>addItem(p)} aria-label={`Add ${p.name} to cart`} className="mt-3 grid size-8 place-items-center rounded-full bg-ink text-white transition hover:scale-105"><Plus size={15}/></button></div></div></article></Reveal>)}</div></div></section>

  <section className="px-4 py-4 sm:px-6 lg:px-8"><div className="grain relative mx-auto max-w-7xl overflow-hidden rounded-[2rem] bg-[#172826] px-7 py-14 text-white sm:px-14 lg:py-20"><div className="absolute -right-28 -top-28 size-96 rounded-full bg-emerald-400/30 blur-3xl"/><div className="relative grid gap-10 lg:grid-cols-2"><div><p className="eyebrow text-emerald-300">A small summer celebration</p><h2 className="display mt-4 text-6xl font-extrabold leading-[.9] sm:text-7xl">Up to 50%<br/>off, naturally.</h2><p className="mt-6 max-w-sm text-sm leading-6 text-white/65">Just the things you were already thinking about. A little more attainable for a little while.</p><Button className="mt-7 bg-white text-ink">Shop summer sale</Button></div><div className="flex items-end lg:justify-end"><div><p className="eyebrow mb-3 text-white/55">Offer ends in</p><div className="flex gap-3">{time.map((t,i)=><div key={i} className="rounded-2xl border border-white/15 bg-white/10 px-4 py-4 text-center backdrop-blur"><strong className="text-3xl">{t}</strong><span className="mt-1 block text-[9px] uppercase tracking-widest text-white/55">{["hours","mins","secs"][i]}</span></div>)}</div></div></div></div></div></section>

  <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><Reveal><p className="eyebrow text-emerald-700">The Luma difference</p><h2 className="display mt-3 text-4xl font-extrabold sm:text-5xl">Good from click to doorstep.</h2></Reveal><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[Truck,"Quick, considered delivery","Free express delivery over $75."],[ShieldCheck,"Secure by design","Your details are always protected."],[PackageCheck,"Returns made easy","30 days to see if it feels right."],[Zap,"Here when you need us","Real support, around the clock."]].map(([Icon,title,text],i)=>{const I=Icon as typeof Truck;return <Reveal delay={i*.08} key={title as string}><div className="rounded-2xl bg-white p-6 shadow-sm"><div className="grid size-10 place-items-center rounded-xl bg-mint"><I size={19}/></div><h3 className="mt-6 font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-black/55">{text as string}</p></div></Reveal>})}</div></section>

  <section id="journal" className="bg-[#e9e7e2] py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Reveal><div className="flex items-end justify-between"><div><p className="eyebrow text-emerald-700">From the people who use it</p><h2 className="display mt-3 text-4xl font-extrabold sm:text-5xl">The word on Luma.</h2></div><div className="hidden gap-2 sm:flex"><button onClick={()=>setActive((active+2)%3)} className="grid size-10 place-items-center rounded-full border border-black/15"><ChevronLeft size={18}/></button><button onClick={()=>setActive((active+1)%3)} className="grid size-10 place-items-center rounded-full bg-ink text-white"><ChevronRight size={18}/></button></div></div></Reveal><div className="mt-10 grid gap-4 md:grid-cols-3">{testimonials.map((t,i)=><motion.article animate={{opacity:i===active?1:.58,scale:i===active?1:.98}} key={t.name} className="rounded-2xl bg-white p-7"><div className="flex gap-1 text-emerald-600">{[...Array(5)].map((_,j)=><Star fill="currentColor" size={15} key={j}/>)}</div><blockquote className="mt-6 text-lg font-semibold leading-8">“{t.quote}”</blockquote><div className="mt-8 flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full bg-mint text-xs font-bold">{t.initials}</div><div><p className="text-sm font-bold">{t.name}</p><p className="text-xs text-black/45">{t.role}</p></div></div></motion.article>)}</div></div></section>
  <section className="mx-auto grid max-w-7xl grid-cols-2 gap-y-8 px-5 py-20 text-center sm:grid-cols-4 sm:px-8">{[["10k+","happy customers"],["5k+","beautiful products"],["99%","say they’d return"],["100+","independent brands"]].map(([num,label],i)=><Reveal delay={i*.08} key={label}><strong className="display text-5xl font-extrabold sm:text-6xl">{num}</strong><p className="mt-2 text-xs text-black/45">{label}</p></Reveal>)}</section>
  <section className="px-4 pb-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl rounded-[2rem] bg-[#b9d3ff] px-7 py-14 text-center sm:px-14"><Reveal><p className="eyebrow">The Luma letter</p><h2 className="display mt-4 text-4xl font-extrabold sm:text-5xl">Something nice, in your inbox.</h2><p className="mx-auto mt-4 max-w-md text-sm leading-6 text-black/60">A well-edited note about new things, quiet offers, and ideas worth sharing. No noise.</p><form onSubmit={e=>{e.preventDefault();if(/\S+@\S+\.\S+/.test(email))setSubscribed(true)}} className="mx-auto mt-7 flex max-w-md flex-col gap-2 sm:flex-row"><label className="sr-only" htmlFor="email">Email address</label><input id="email" required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Your email address" className="min-w-0 flex-1 rounded-full border border-black/10 bg-white/85 px-5 py-3 text-sm outline-none focus:ring-2 focus:ring-ink"/>{subscribed?<span className="flex items-center justify-center gap-1 rounded-full bg-ink px-5 py-3 text-sm font-bold text-white"><Check size={16}/> You&apos;re in</span>:<Button type="submit">Subscribe</Button>}</form></Reveal></div></section>
  <footer id="about" className="mx-auto max-w-7xl px-5 pb-7 pt-16 sm:px-8"><div className="grid gap-10 border-b border-black/10 pb-12 sm:grid-cols-2 lg:grid-cols-[2fr_1fr_1fr_1fr]"><div><a className="text-3xl font-extrabold tracking-[-.1em]" href="#top">luma<span className="text-emerald-500">.</span></a><p className="mt-4 max-w-xs text-sm leading-6 text-black/50">For the things that make everyday life feel a little more considered.</p></div>{[["Shop","New arrivals|Best sellers|Summer sale|Gift cards"],["About","Our story|Journal|Careers|Contact"],["Help","Shipping & returns|FAQs|Accessibility|Privacy"]].map(([title,links])=><div key={title}><p className="eyebrow">{title}</p><div className="mt-4 flex flex-col gap-2 text-sm text-black/55">{links.split('|').map(x=><a className="hover:text-ink" href="#" key={x}>{x}</a>)}</div></div>)}</div><div className="flex flex-col justify-between gap-3 pt-6 text-xs text-black/45 sm:flex-row"><p>© 2026 Luma Supply Co. All rights reserved.</p><div className="flex gap-5"><a href="#">Instagram</a><a href="#">Pinterest</a><a href="#">Terms</a></div><a href="#top" className="font-bold text-ink">Back to top ↑</a></div></footer>
 </main>;
}
