"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { Check, ChevronDown, Heart, Minus, PackageCheck, Plus, ShieldCheck, Star, Truck } from "lucide-react";
import { useState } from "react";
import type { Product } from "@/lib/data";
import { products } from "@/lib/data";
import { useCart } from "@/context/CartContext";
import { CartBadge } from "@/components/cart/CartBadge";

const reviews = [
  { name: "Sofia R.", date: "2 weeks ago", rating: 5, copy: "The finish is even better in person. It feels considered in all the little ways that matter." },
  { name: "Daniel K.", date: "1 month ago", rating: 5, copy: "Beautifully made, beautifully packaged, and it arrived sooner than expected." },
  { name: "Avery M.", date: "1 month ago", rating: 4, copy: "Thoughtful details and excellent quality. It has become part of my daily routine." },
];

export function ProductDetails({ product }: { product: Product }) {
  const [selectedImage, setSelectedImage] = useState(0);
  const [quantity, setQuantity] = useState(1);
  const [specificationsOpen, setSpecificationsOpen] = useState(false);
  const { addItem, openCart } = useCart();
  const related = products.filter((item) => item.id !== product.id).slice(0, 3);
  const addToCart = () => addItem(product, quantity);
  const buyNow = () => { addToCart(); openCart(); };

  return <main className="min-h-screen bg-white pb-24 sm:pb-0">
    <header className="sticky top-0 z-40 border-b border-black/5 bg-white/80 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 sm:px-8"><Link href="/" className="text-2xl font-extrabold tracking-[-.1em]" aria-label="Luma home">luma<span className="text-emerald-500">.</span></Link><div className="hidden items-center gap-6 text-sm font-semibold sm:flex"><Link href="/#shop" className="transition hover:text-emerald-600">Shop</Link><Link href="/#categories" className="transition hover:text-emerald-600">Categories</Link><Link href="/#journal" className="transition hover:text-emerald-600">Journal</Link></div><CartBadge/></div></header>
    <div className="mx-auto max-w-7xl px-5 py-6 sm:px-8"><nav aria-label="Breadcrumb" className="flex items-center gap-2 text-xs text-black/45"><Link href="/" className="hover:text-ink">Home</Link><span>/</span><Link href="/#shop" className="hover:text-ink">{product.category}</Link><span>/</span><span className="truncate text-black/70">{product.name}</span></nav></div>
    <section className="mx-auto grid max-w-7xl gap-10 px-5 pb-20 sm:px-8 lg:grid-cols-[1.1fr_.9fr] lg:gap-16">
      <motion.div initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .5 }} className="min-w-0"><div className="flex gap-3"><div className="hidden w-20 shrink-0 flex-col gap-3 sm:flex">{product.gallery.map((image, index) => <button key={image} onClick={() => setSelectedImage(index)} aria-label={`View image ${index + 1}`} className={`overflow-hidden rounded-xl border-2 transition ${selectedImage === index ? "border-ink" : "border-transparent hover:border-black/20"}`}><img src={image} alt="" className="aspect-square w-full object-cover"/></button>)}</div><div className="group relative min-w-0 flex-1 overflow-hidden rounded-[1.75rem] bg-cloud"><img src={product.gallery[selectedImage]} alt={`${product.name}, view ${selectedImage + 1}`} className="aspect-square w-full object-cover transition duration-700 ease-out lg:group-hover:scale-110"/><span className="absolute left-4 top-4 rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase tracking-wider">{product.badge}</span><span className="absolute bottom-4 right-4 hidden rounded-full bg-white/80 px-3 py-2 text-[10px] font-bold text-black/55 backdrop-blur sm:block">Hover to zoom</span></div></div><div className="mt-3 flex gap-3 overflow-x-auto sm:hidden">{product.gallery.map((image, index) => <button key={image} onClick={() => setSelectedImage(index)} aria-label={`View image ${index + 1}`} className={`w-16 shrink-0 overflow-hidden rounded-xl border-2 ${selectedImage === index ? "border-ink" : "border-transparent"}`}><img src={image} alt="" className="aspect-square w-full object-cover"/></button>)}</div></motion.div>
      <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .55, delay: .08 }} className="lg:pt-5"><p className="eyebrow text-emerald-700">{product.category}</p><div className="mt-3 flex items-start justify-between gap-5"><h1 className="display text-5xl font-extrabold leading-[.95] sm:text-6xl">{product.name}</h1><button aria-label={`Add ${product.name} to wishlist`} className="grid size-11 shrink-0 place-items-center rounded-full border border-black/10 transition hover:bg-ink hover:text-white"><Heart size={19}/></button></div><div className="mt-5 flex items-center gap-3"><span className="flex items-center gap-1 text-sm font-bold"><Star size={15} fill="currentColor" className="text-emerald-600"/> {product.rating}</span><span className="text-sm text-black/35">{product.reviews} considered reviews</span></div><div className="mt-7 flex items-end gap-3"><p className="text-3xl font-extrabold">${product.price}</p>{product.old > 0 && <><p className="mb-1 text-sm text-black/35 line-through">${product.old}</p><span className="mb-1 rounded-full bg-mint px-2 py-1 text-[10px] font-bold text-emerald-900">Save ${product.old - product.price}</span></>}</div><div className="mt-7 rounded-2xl bg-cloud p-5"><p className="text-sm leading-7 text-black/65">{product.description}</p></div><div className="mt-7 flex items-center gap-2 text-xs font-bold text-emerald-700"><span className="size-2 rounded-full bg-emerald-500"/> In stock and ready to ship</div>
        <div className="mt-7 flex gap-3"><div className="flex items-center rounded-full border border-black/10 p-1"><button onClick={() => setQuantity((current) => Math.max(1, current - 1))} aria-label="Decrease quantity" disabled={quantity === 1} className="grid size-10 place-items-center rounded-full transition hover:bg-cloud disabled:cursor-not-allowed disabled:opacity-35"><Minus size={16}/></button><span className="w-8 text-center text-sm font-bold">{quantity}</span><button onClick={() => setQuantity((current) => current + 1)} aria-label="Increase quantity" className="grid size-10 place-items-center rounded-full transition hover:bg-cloud"><Plus size={16}/></button></div><button onClick={addToCart} className="flex flex-1 items-center justify-center gap-2 rounded-full bg-ink px-5 py-3.5 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:shadow-lg">Add to bag <span aria-hidden>→</span></button></div><button onClick={buyNow} className="mt-3 w-full rounded-full border border-black/15 px-5 py-3.5 text-sm font-bold transition hover:bg-cloud">Buy now</button>
        <div className="mt-8 grid grid-cols-3 gap-2 border-y border-black/8 py-5 text-center"><div><Truck className="mx-auto" size={18}/><p className="mt-2 text-[10px] font-bold">Free delivery</p></div><div><ShieldCheck className="mx-auto" size={18}/><p className="mt-2 text-[10px] font-bold">Secure payment</p></div><div><PackageCheck className="mx-auto" size={18}/><p className="mt-2 text-[10px] font-bold">30-day returns</p></div></div>
        <div className="mt-8"><p className="eyebrow">Made to live with</p><ul className="mt-4 grid gap-3 sm:grid-cols-2">{product.features.map((feature) => <li key={feature} className="flex items-center gap-2 text-sm text-black/65"><span className="grid size-5 place-items-center rounded-full bg-mint"><Check size={12}/></span>{feature}</li>)}</ul></div>
        <div className="mt-9 border-t border-black/10"><button onClick={() => setSpecificationsOpen((open) => !open)} aria-expanded={specificationsOpen} className="flex w-full items-center justify-between py-5 text-left text-sm font-bold">Specifications <ChevronDown size={18} className={`transition ${specificationsOpen ? "rotate-180" : ""}`}/></button>{specificationsOpen && <motion.dl initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} className="grid grid-cols-2 gap-x-6 gap-y-4 overflow-hidden pb-5 text-sm">{product.specs.map((spec) => <div key={spec.label}><dt className="text-black/40">{spec.label}</dt><dd className="mt-1 font-semibold">{spec.value}</dd></div>)}</motion.dl>}</div>
      </motion.div>
    </section>
    <section className="bg-[#e9e7e2] py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="max-w-2xl"><p className="eyebrow text-emerald-700">From people who use it</p><h2 className="display mt-3 text-4xl font-extrabold sm:text-5xl">The details add up.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3">{reviews.map((review) => <article key={review.name} className="rounded-2xl bg-white p-6"><div className="flex gap-1 text-emerald-600">{Array.from({ length: review.rating }, (_, index) => <Star key={index} size={14} fill="currentColor"/>)}</div><p className="mt-5 text-sm font-semibold leading-7">“{review.copy}”</p><div className="mt-7"><p className="text-sm font-bold">{review.name}</p><p className="mt-1 text-xs text-black/40">{review.date} · Verified buyer</p></div></article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="flex items-end justify-between"><div><p className="eyebrow text-emerald-700">Keep looking</p><h2 className="display mt-3 text-4xl font-extrabold sm:text-5xl">Works well with.</h2></div><Link href="/#shop" className="hidden text-sm font-bold sm:block">View the whole edit →</Link></div><div className="mt-10 grid gap-5 sm:grid-cols-3">{related.map((item) => <Link key={item.id} href={`/product/${item.id}`} className="group"><div className="overflow-hidden rounded-2xl bg-cloud"><img src={item.image} alt={item.name} className="aspect-square w-full object-cover transition duration-700 group-hover:scale-105"/></div><div className="flex items-start justify-between pt-4"><div><p className="text-[11px] text-black/45">{item.category}</p><h3 className="mt-1 text-sm font-bold">{item.name}</h3></div><p className="text-sm font-bold">${item.price}</p></div></Link>)}</div></section>
    <div className="fixed inset-x-0 bottom-0 z-30 border-t border-black/10 bg-white/90 p-3 backdrop-blur lg:hidden"><div className="mx-auto flex max-w-lg items-center gap-3"><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{product.name}</p><p className="text-sm font-extrabold">${product.price}</p></div><button onClick={addToCart} className="rounded-full bg-ink px-5 py-3 text-sm font-bold text-white">Add to bag</button></div></div>
  </main>;
}
